services:
  web:
    image: aidang/encounter-builder:latest
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
    secrets:
      - db_password
  frontend:
    image: aidang/encounter-builder-ui-dev:latest
    volumes:
      - type: bind
        source: ../svelte/src
        target: /application/src
    ports:
      - "5173:5173"
    networks:
      - frontend
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: encounter-builder
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - backend
    secrets:
      - db_password
networks:
  backend:
    name: backend
  frontend:
    name: frontend
secrets:
  db_password:
    file: ./secrets/db_password.txt