-- These ENUMs aren't actually used, because JDBC doesn't support it

CREATE TYPE damage_type AS ENUM (
    'SLASHING',
    'PIERCING',
    'BLUDGEONING',
    'POISON',
    'ACID',
    'FIRE',
    'COLD',
    'RADIANT',
    'NECROTIC',
    'LIGHTNING',
    'THUNDER',
    'FORCE',
    'PYSCHIC'
);

CREATE TYPE die AS ENUM (
    'D3',
    'D4',
    'D6',
    'D8',
    'D10',
    'D12',
    'D20',
    'D100'
);

CREATE TYPE creature_size AS ENUM (
    'TINY',
    'SMALL',
    'MEDIUM',
    'LARGE',
    'HUGE',
    'GARGANTUAN'
);

CREATE TYPE ability AS ENUM (
    'STRENGTH',
    'DEXTERITY',
    'CONSTITUTION',
    'INTELLIGENCE',
    'WISDOM',
    'CHARISMA'
);

CREATE TABLE if not exists encounter (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text
);

CREATE TABLE if not exists template_creature (
     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name text NOT NULL,
     description text,
     hitpoints int,
     creature_size text,
     type text,
     alignment text,
     armor_class int,
     dice_die text,
     dice_count int,
     speed_walk int,
     speed_climb int,
     speed_fly int,
     speed_swim int,
     ability_strength int,
     ability_dexterity int,
     ability_constitution int,
     ability_intelligence int,
     ability_wisdom int,
     ability_charisma int,
     saving_throws text[]
);

CREATE TABLE if not exists encounter_creature_ref (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    encounter int NOT NULL,
    encounter_key int,
    template_creature int NOT NULL,
    template_creature_key int,
    count int,
    UNIQUE(encounter, template_creature),
    FOREIGN KEY (encounter) REFERENCES encounter(id),
    FOREIGN KEY (template_creature) REFERENCES template_creature(id)
);

CREATE TABLE if not exists attack (
     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     template_creature int,
     template_creature_key int,
     name text NOT NULL,
     description text,
     range text,
     FOREIGN KEY (template_creature) REFERENCES template_creature(id)
);

CREATE TABLE if not exists damage (
     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     TODO: remove this undesirable reverse mapping
     attack int,
     attack_key int,
     die text NOT NULL,
     count int NOT NULL,
     damage_type text NOT NULL,
     FOREIGN KEY (attack) REFERENCES attack(id)
);