CREATE TABLE if not exists encounter (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text
);

CREATE TABLE if not exists template_creature (
     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name text NOT NULL,
     description text,
     hp int
);